accounts/api/urls.py
from django.urls import path
from .views import *

app_name = 'accounts-api'

urlpatterns = [
    path("login/", loginView.as_view(), name="login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("activate/<slug>/", ActivationView.as_view(), name="activate"),
    
]

accounts/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views

app_name = 'accounts'
urlpatterns = [
    # path("login/",login_view, name="login"),
    # path("logout/",logout_view, name="logout"),
    # path("register/",register_view, name="register"),
    # path("activate/account/<activation_code>/",activate_account_view, name="activate-account"),
    # path("activate/<slug>/",activate_account_code_view, name="activate")
]

core/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')) ,
    path('api/',include('products.api.urls')) ,
    path('api/accounts/',include('accounts.api.urls')) ,
    path('accounts/',include('accounts.urls')) ,
    path('users/',include('users.urls')) ,
]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", register_view, name="register"),
    path("change-password/", password_change_view, name="change-password"),
    path("reset/", reset_password_view, name="reset"),
    path("reset-complete/<slug>/", reset_complete_view, name="reset-complete"),
    path("activate/<slug>/", account_activate_view, name="activate")

]

accounts/models.py
from django.db import models
from services.mixin import DateMixin,SlugMixin
from django.contrib.auth import get_user_model
from services.uploader import Uploader
from ckeditor.fields import RichTextField
from phonenumber_field.modelfields import PhoneNumberField
from services.generator import CodeGenerator
from django.utils.text import slugify
from services.slugify import slugify
# Create your models here.

User = get_user_model()

class Profile(DateMixin):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = RichTextField(blank=True,null=True)
    age = models.PositiveIntegerField(blank=True,null=True)
    activation_code = models.CharField(max_length=200, blank=True,null=True)
    slug = models.SlugField(unique=True, blank=True,null=True)

    def __str__(self):
        return self.user.email

    def save(self,*args, **kwargs):
        self.slug = CodeGenerator.create_slug_profile(size=10, model_=Profile)

        
        return super().save(*args, **kwargs)
    










class Company(DateMixin,SlugMixin):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    name = models.CharField(max_length=300)
    logo = models.ImageField(upload_to = Uploader.upload_logo_company)
    adress = RichTextField()
    description = RichTextField()
    mobile = PhoneNumberField()


    def __str__(self):
        return self.name

    class Meta:
        ordering = ("-created_at",)
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'


    def save(self,*args, **kwargs):
        self.code = CodeGenerator.create_slug_shortcode(size=10, model_=Company)

        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)
    

accounts/forms.py
# from django import forms
# from .models import User,Profile
# from django.contrib.auth import authenticate
# class LoginForm(forms.ModelForm):
#     password=forms.CharField(widget=forms.PasswordInput)
#     class Meta:
#         model = User
#         fields = ("username","password")


#     def __init__(self,*args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for field in self.fields:
#             self.fields[field].widget.attrs.update({'class':'form-control'})


#     def clean(self):
#         attrs = self.cleaned_data

#         username = attrs.get('username')
#         password = attrs.get('password')

#         user = authenticate(username=username ,password=password)

#         if not user:
#             raise forms.ValidationError('This user does not exists...')


#         if not user.is_active:
#             raise forms.ValidationError('This user is not active...')

#         if not user.check_password(password):
#             raise forms.ValidationError('Username or password is wrong...')

#         return attrs


# class RegisterForm(forms.ModelForm):
#     password=forms.CharField(widget=forms.PasswordInput)
#     password_confirm=forms.CharField(widget=forms.PasswordInput)
#     class Meta:
#         model = User
#         fields = ('username','email','first_name','last_name','password','password_confirm')

#     def __init__(self,*args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for field in self.fields:
#             self.fields[field].widget.attrs.update({
#                 'class':'form-control',
#                 'placeholder': f'{self.fields[field].label}'                
#                 })

#     def clean(self):
#         attrs = self.cleaned_data

#         username = attrs.get('username')
#         password = attrs.get('password')
#         password_confirm = attrs.get('password_confirm')

#         # user = authenticate(username = username , password = password)
#         user_qs = User.objects.filter(username = username)


#         if user_qs.exists():
#             raise forms.ValidationError('This username already exists')

#         if len(password) < 6:
#             raise forms.ValidationError('This password too short')

#         if password != password_confirm:
#             raise forms.ValidationError('Passwords dont match')

#         if not password.strip()[0].isalpha() :
#             raise forms.ValidationError('Password must begin with letter')

#         if not password.isalnum():
#             raise forms.ValidationError('Password must contains at least 1 number and 1 symbol ')

#         return attrs
    

accounts/api/views.py
from rest_framework import generics
from .serializers import LoginSerializer,RegisterSerializer,ActivationSerializer
from django.contrib.auth import get_user_model
from rest_framework.response import Response
from rest_framework_simplejwt.tokens import RefreshToken

User = get_user_model()

class loginView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = LoginSerializer


    def post(self, request,*args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)

        return Response(serializer.data,status=201)




class RegisterView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = RegisterSerializer


class ActivationView(generics.GenericAPIView):
    queryset = User.objects.all()
    serializer_class = ActivationSerializer
    lookup_field = 'slug'


    def put(self,request,*args, **kwargs):
        obj = self.get_object()
        data = {}
        if obj.activation_code==request.data.get('code'):
            obj.is_active = True
            obj.activation_code = None
            obj.save()
            token = RefreshToken.for_user(obj)
            data['email'] = obj.email
            data['token'] = {'refresh':str(token),'access':str(token.access_token)}
            return Response(data,status=201)


        else:
            return Response({'error' : 'Wrong code'})

accounts/views.py
# from django.shortcuts import render,redirect,get_object_or_404
# from .models import User,Profile
# from .forms import *
# from django.contrib.auth import authenticate , login,logout
# from django.core.mail import send_mail
# from services.generator import CodeGenerator
# from django.conf import settings
# from django.urls import reverse_lazy
# # Create your views here.

# def login_view(request):
#     form=LoginForm()

#     if request.method == 'POST':
#         form = LoginForm(request.POST)

#         if form.is_valid():
#             username = form.cleaned_data.get('username')
#             password = form.cleaned_data.get('password')
#             user = authenticate(username=username,password=password)
#             login(request, user)
#             return redirect('/accounts/login/')

#     context = {
#         'form':form
#     }

#     return render(request, 'accounts/login.html',context)


# def logout_view(request):
#     logout(request)
#     return redirect('/')



# def register_view(request):

#     form = RegisterForm()

#     if request.method == 'POST':
#         form = RegisterForm(request.POST or None)

#         if form.is_valid():
#             new_user = form.save(commit=False)
#             new_user.is_active = False
#             new_user.save()
#             # profile = Profile.objects.create(
#             #     user=new_user,
#             #     activation_code=CodeGenerator.create_activation_link_code(
#             #         size=30,model_=Profile
#             #     )
#             # )

#             profile = Profile.objects.create(
#                 user=new_user,
#                 activation_code=CodeGenerator.create_activation_link_code(
#                     size=4,model_=Profile
#                 )
#             )
        
#             # link =request.build_absolute_uri(f'/accounts/activate/account/{profile.activation_code}/')
#             # message = f"Please click the link below: \n{link}"
#             message = f"Please write code below: \n{profile.activation_code}"

        

#             # send email
#             send_mail(
#                 'Activate Email',
#                 message,
#                 settings.EMAIL_HOST_USER,
#                 [new_user.email],
#                 fail_silently=False,
#             )
        
#             return redirect(reverse_lazy("accounts:activate", kwargs={"slug": profile.slug}))

#     context = {
#         'form' : form
#     }
#     return render(request, 'accounts/register.html',context)



# def activate_account_view(request , activation_code):
#     profile = get_object_or_404(Profile,activation_code=activation_code)
#     profile.user.is_active = True
#     profile.activation_code = None
#     profile.user.save()
#     profile.save()
#     login(request, profile.user)
#     return redirect('/')

# def activate_account_code_view(request,slug):
#     profile = get_object_or_404(Profile,slug=slug)
#     if request.method == "POST":
#         code = request.POST.get("code")
    
#         if code == profile.activation_code:
#             profile.user.is_active = True
#             profile.activation_code = None
#             profile.user.save()
#             profile.save()
#             login(request, profile.user)
#             return redirect('/')
#     return render(request, "accounts/activate.html", {})

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <!-- mobile fix menu start -->
    <div class="mobile-menu d-md-none d-block mobile-cart">
        <ul>
            <li class="active">
                <a href="index.html">
                    <i class="iconly-Home icli"></i>
                    <span>Home</span>
                </a>
            </li>

            <li class="mobile-category">
                <a href="javascript:void(0)">
                    <i class="iconly-Category icli js-link"></i>
                    <span>Category</span>
                </a>
            </li>

            <li>
                <a href="search.html" class="search-box">
                    <i class="iconly-Search icli"></i>
                    <span>Search</span>
                </a>
            </li>

            <li>
                <a href="wishlist.html" class="notifi-wishlist">
                    <i class="iconly-Heart icli"></i>
                    <span>My Wish</span>
                </a>
            </li>

            <li>
                <a href="cart.html">
                    <i class="iconly-Bag-2 icli fly-cate"></i>
                    <span>Cart</span>
                </a>
            </li>
        </ul>
    </div>
    <!-- mobile fix menu end -->

    <!-- Breadcrumb Section Start -->
    <section class="breadscrumb-section pt-0">
        <div class="container-fluid-lg">
            <div class="row">
                <div class="col-12">
                    <div class="breadscrumb-contain">
                        <h2 class="mb-2">Log In</h2>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- log in section start -->
    <section class="log-in-section background-image-2 section-b-space">
        <div class="container-fluid-lg w-100">
            <div class="row">
                <div class="col-xxl-6 col-xl-5 col-lg-6 d-lg-block d-none ms-auto">
                    <div class="image-contain">
                        <img src="/static/assets/images/inner-page/log-in.png" class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-xxl-4 col-xl-5 col-lg-6 col-sm-8 mx-auto">
                    <div class="log-in-box">
                        <div class="log-in-title">
                            <h3>Welcome To Fastkart</h3>
                            <h4>Log In Your Account</h4>
                        </div>

                        <div class="input-box">
                            <form class="row g-4" method="POST">
                                {% csrf_token %}
                                <div class="col-12">
                                    <div class="form-floating theme-form-floating log-in-form">
<!--                                        <input type="email" class="form-control" id="email" placeholder="Email Address">-->
<!--                                        <label for="email">Email Address</label>-->
                                        {{ form.email.label }}
                                        {{ form.email }}
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating theme-form-floating log-in-form">
                                       <!-- <input type="password" class="form-control" id="password"-->
<!--                                            placeholder="Password">-->
<!--                                        <label for="password">Password</label> -->

                                            {{ form.password.label }}
                                            {{ form.password }}
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="forgot-box">
                                        <div class="form-check ps-0 m-0 remember-box">
<!--                                            <input class="checkbox_animated check-box" type="checkbox"-->
<!--                                                id="flexCheckDefault">-->
<!--                                            <label class="form-check-label" for="flexCheckDefault">Remember me</label>-->
                                        </div>
                                        <a href="{% url 'users:reset' %}" class="forgot-password">Forgot Password?</a>
                                    </div>
                                </div>

                                <div class="col-12">  
                                    <button class="btn btn-animation w-100 justify-content-center" type="submit">Log
                                        In</button>
                                </div>
                            </form>
                        </div>

<!--                        <div class="other-log-in">-->
<!--                            <h6>or</h6>-->
<!--                        </div>-->

<!--                        <div class="log-in-button">-->
<!--                            <ul>-->
<!--                                <li>-->
<!--                                    <a href="https://www.google.com/" class="btn google-button w-100">-->
<!--                                        <img src="/static/assets/images/inner-page/google.png" class="blur-up lazyload"-->
<!--                                            alt=""> Log In with Google-->
<!--                                    </a>-->
<!--                                </li>-->
<!--                                <li>-->
<!--                                    <a href="https://www.facebook.com/" class="btn google-button w-100">-->
<!--                                        <img src="/static/assets/images/inner-page/facebook.png" class="blur-up lazyload"-->
<!--                                            alt=""> Log In with Facebook-->
<!--                                    </a>-->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->

                        <div class="other-log-in">
                            <h6></h6>
                        </div>

                        <div class="sign-up-box">
                            <h4>Don't have an account?</h4>
                            <a href="{% url 'users:register' %}">Sign Up</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- log in section end -->


{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <!-- mobile fix menu start -->
    <div class="mobile-menu d-md-none d-block mobile-cart">
        <ul>
            <li class="active">
                <a href="index.html">
                    <i class="iconly-Home icli"></i>
                    <span>Home</span>
                </a>
            </li>

            <li class="mobile-category">
                <a href="javascript:void(0)">
                    <i class="iconly-Category icli js-link"></i>
                    <span>Category</span>
                </a>
            </li>

            <li>
                <a href="search.html" class="search-box">
                    <i class="iconly-Search icli"></i>
                    <span>Search</span>
                </a>
            </li>

            <li>
                <a href="wishlist.html" class="notifi-wishlist">
                    <i class="iconly-Heart icli"></i>
                    <span>My Wish</span>
                </a>
            </li>

            <li>
                <a href="cart.html">
                    <i class="iconly-Bag-2 icli fly-cate"></i>
                    <span>Cart</span>
                </a>
            </li>
        </ul>
    </div>
    <!-- mobile fix menu end -->

    <!-- Breadcrumb Section Start -->
    <section class="breadscrumb-section pt-0">
        <div class="container-fluid-lg">
            <div class="row">
                <div class="col-12">
                    <div class="breadscrumb-contain">
                        <h2 class="mb-2" style="color: cadetblue;">REGISTER</h2>
                        <nav>
                            
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- log in section start -->
    <section class="log-in-section background-image-2 section-b-space">
        <div class="container-fluid-lg w-100">
            <div class="row">
                <div class="col-xxl-6 col-xl-5 col-lg-6 d-lg-block d-none ms-auto">
                    <div class="image-contain">
                        <img src="/static/assets/images/inner-page/log-in.png" class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-xxl-4 col-xl-5 col-lg-6 col-sm-8 mx-auto">
                    <div class="log-in-box">
                        <div class="log-in-title">
                            <h3>Welcome To Fastkart</h3>
                            <h4>Log In Your Account</h4>
                        </div>

                        <div class="input-box">
                            <form class="row g-4" method="POST">
                                {% csrf_token %}

                                <div class="col-12">
                                    <div class="form-floating theme-form-floating log-in-form">
                                       <!-- <input type="password" class="form-control" id="password"-->
<!--                                            placeholder="Password">-->
<!--                                        <label for="password">Password</label> -->

                                            {{ form.email.label }}
                                            {{ form.email }}
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating theme-form-floating log-in-form">
                                       <!-- <input type="password" class="form-control" id="password"-->
<!--                                            placeholder="Password">-->
<!--                                        <label for="password">Password</label> -->

                                            {{ form.full_name.label }}
                                            {{ form.full_name }}
                                    </div>
                                </div>


                                <div class="col-12">
                                    <div class="form-floating theme-form-floating log-in-form">
                                       <!-- <input type="password" class="form-control" id="password"-->
<!--                                            placeholder="Password">-->
<!--                                        <label for="password">Password</label> -->

                                            {{ form.password1.label }}
                                            {{ form.password1 }}
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating theme-form-floating log-in-form">
<!--                                        <input type="email" class="form-control" id="email" placeholder="Email Address">-->
<!--                                        <label for="email">Email Address</label>-->
                                        {{ form.password2.label }}
                                        {{ form.password2}}
                                    </div>
                                </div>

 

                                <div class="col-12">
                                    <button class="btn btn-animation w-100 justify-content-center" type="submit">Register</button>
                                </div>
                                

                            </form>
                        </div>

<!--                        <div class="other-log-in">-->
<!--                            <h6>or</h6>-->
<!--                        </div>-->

<!--                        <div class="log-in-button">-->
<!--                            <ul>-->
<!--                                <li>-->
<!--                                    <a href="https://www.google.com/" class="btn google-button w-100">-->
<!--                                        <img src="/static/assets/images/inner-page/google.png" class="blur-up lazyload"-->
<!--                                            alt=""> Log In with Google-->
<!--                                    </a>-->
<!--                                </li>-->
<!--                                <li>-->
<!--                                    <a href="https://www.facebook.com/" class="btn google-button w-100">-->
<!--                                        <img src="/static/assets/images/inner-page/facebook.png" class="blur-up lazyload"-->
<!--                                            alt=""> Log In with Facebook-->
<!--                                    </a>-->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->

                        <div class="other-log-in">
                            <h6></h6>
                        </div>

                        <div class="sign-up-box">
                            <h4>Already have an account?</h4>
                            <a href="{% url 'users:login' %}">Log In</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- log in section end -->


{% endblock %}