core/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')) ,
    path('api/',include('products.api.urls')) ,
    path('api/accounts/',include('accounts.api.urls')) ,
    path('accounts/',include('accounts.urls')) ,
    path('users/',include('users.urls')) ,
]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path("",index_view, name="index"),
    path("create/",create_view, name="create"),
    path("wish/",product_wish_view, name="wish"),
    path("basket/",product_basket_view, name="basket"),
    path("wishlist/",wishlist_view, name="wishlist"),
    path("basket-list/",basket_list_view, name="basket-list"),
    path("delete-item/",delete_item_from_basket, name="delete-item"),
]

templates/baskets/cart.html
{% extends 'base.html' %}
{% load static %}
 
{% block body %}
    <!-- Breadcrumb Section Start -->
    <section class="breadscrumb-section pt-0">
        {% csrf_token %}
        <div class="container-fluid-lg">
            <div class="row">
                <div class="col-12">
                    <div class="breadscrumb-contain">
                        <h2>Cart</h2>
                        <nav>
                            <ol class="breadcrumb mb-0">
                                <li class="breadcrumb-item">
                                    <a href="index.html">
                                        <i class="fa-solid fa-house"></i>
                                    </a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">Cart</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Cart Section Start -->
    <section class="cart-section section-b-space">
        <div class="container-fluid-lg">
            <form method="POST">
                {% csrf_token %}
                    <div class="row g-sm-5 g-3">
                        <div class="col-xxl-9">
                            <div class="cart-table">
                                <div class="table-responsive-xl">
                                    <table class="table">
                                        <tbody>
                                            {% for basket in baskets %}
                                            <tr class="product-box-contain" id="itemDiv-{{basket.id}}">
                                                <td class="product-detail">
                                                    <div class="product border-0">
                                                        <a href="product-left-thumbnail.html" class="product-image">
                                                            <img src="{{basket.product.productimage_set.first.image.url}}"
                                                                class="img-fluid blur-up lazyload" alt="">
                                                        </a>
                                                        <div class="product-detail">
                                                            <ul>
                                                                <li class="name">
                                                                    <a href="product-left-thumbnail.html">{{basket.product.name}}</a>
                                                                </li>

                                                                <li class="text-content"><span class="text-title">
                                                                        By:</span> {{basket.product.company.name}}</li>

                                                                <li class="text-content"><span
                                                                        class="text-title"></span> </li>

        <!--                                                        <li>-->
        <!--                                                            <h5 class="text-content d-inline-block">Price :</h5>-->
        <!--                                                            <span>$35.10</span>-->
        <!--                                                            <span class="text-content">$45.68</span>-->
        <!--                                                        </li>-->

        <!--                                                        <li>-->
        <!--                                                            <h5 class="saving theme-color">Saving : $20.68</h5>-->
        <!--                                                        </li>-->

<!--                                                                <li class="quantity-price-box">-->
<!--                                                                    <div class="cart_qty">-->
<!--                                                                        <div class="input-group">-->
<!--                                                                            <button type="button" class="btn qty-left-minus"-->
<!--                                                                                data-type="minus" data-field="">-->
<!--                                                                                <i class="fa fa-minus ms-0"-->
<!--                                                                                    aria-hidden="true"></i>-->
<!--                                                                            </button>-->
<!--                                                                            <input class="form-control input-number qty-input"-->
<!--                                                                                type="text" name="quantity-{{basket.id}}" value="0">-->
<!--                                                                            <button type="button" class="btn qty-right-plus"-->
<!--                                                                                data-type="plus" data-field="">-->
<!--                                                                                <i class="fa fa-plus ms-0"-->
<!--                                                                                    aria-hidden="true"></i>-->
<!--                                                                            </button>-->
<!--                                                                        </div>-->
<!--                                                                    </div>-->
<!--                                                                </li>-->

                                                                <li>
                                                                    <h5>Total: $35.10</h5>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </td>

                                                <td class="price">
                                                    <h4 class="table-title text-content">Price</h4>
                                                    <h5>{{basket.product_total_price|floatformat:2}} AZN</h5>
                                                </td>

                                                <td class="quantity">
                                                    <h4 class="table-title text-content">Qty</h4>
                                                    <div class="quantity-price">
                                                        <div class="cart_qty">
                                                            <div class="input-group">
                                                                <button type="button" class="btn "
                                                                        onclick="minusQty('{{basket.id}}')"
                                                                    data-type="minus" data-field="">
                                                                    <i class="fa fa-minus ms-0" aria-hidden="true"></i>
                                                                </button>
                                                                <input class="form-control input-number qty-input" type="text"
                                                                       id="item-{{basket.id}}"
                                                                    name="quantity-{{basket.id}}" value="1">
                                                                <button type="button" class="btn"
                                                                        onclick="plusQty('{{basket.id}}')"
                                                                    data-type="plus" data-field="">
                                                                    <i class="fa fa-plus ms-0" aria-hidden="true"></i>
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </td>

                                                <td class="subtotal">
                                                    <h4 class="table-title text-content">Total</h4>
                                                    <h5 class="item-total-price" id="item-total-{{basket.id}}" data-total="{{basket.product_total_price}}">{{basket.product_total_price|floatformat:2}}</h5>
                                                </td>

                                                <td class="save-remove">
                                                    <h4 class="table-title text-content">Action</h4>
        <!--                                            <a class="save notifi-wishlist" href="javascript:void(0)">Save for later</a>-->
                                                    <a class="remove close_button" onclick="removeItem('{{basket.id}}')">Remove</a>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                        <div class="col-xxl-3">
                            <div class="summery-box p-sticky">
                                <div class="summery-header">
                                    <h3>Cart Total</h3>
                                </div>

                                <ul class="summery-total">
                                    <li class="list-total border-top-0">
                                        <h4>Total (AZN)</h4>
                                        <h4 class="price theme-color" id="basket-total-price">{{ basket_total_price|floatformat:2 }} AZN</h4>
                                    </li>
                                </ul>

                                <div class="button-group cart-button">
                                    <ul>
                                        <li>
                                            <button type="submit"
                                                class="btn btn-animation proceed-btn fw-bold">Process To Checkout</button>
                                        </li>

                                        <li>
                                            <button onclick="location.href = 'index.html';"
                                                class="btn btn-light shopping-button text-dark">
                                                <i class="fa-solid fa-arrow-left-long"></i>Return To Shopping</button>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
            </form>
        </div>
    </section>
    <!-- Cart Section End -->
    {% endblock  %}

    {% block js %}
    <script>
        var delete_item_url = "{% url 'products:delete-item' %}"
        function calculateTotalPrice(){
        var item_price = $(".item-total-price")
        total_price = 0
        for(i=0;i<item_price.length;i++){
            total_price = total_price + parseFloat(item_price[i].innerText)
        }
        $("#basket-total-price").text(total_price)
    }

        function plusQty(id){
            value = parseInt($("#item-"+id).val())
            total_price = $("#item-total-"+id).attr("data-total")
            $("#item-"+id).val(value+1)
            $("#item-total-"+id).text(parseFloat(total_price)*(value+1))
            calculateTotalPrice()
        }

        function minusQty(id){
            value = parseInt($("#item-"+id).val())
            total_price = $("#item-total-"+id).attr("data-total")
            if(!(value-1)<1){
                $("#item-"+id).val(value-1)
                $("#item-total-"+id).text(parseFloat(total_price)*(value-1))
                calculateTotalPrice()
            }
            
        }

        function removeItem(id){
            var myHeaders = new Headers()
            myHeaders.append('X-CSRFToken', document.querySelector('[name=csrfmiddlewaretoken]').value)
            var formData = new FormData()

            formData.append('id', id)

            var requestOptions = {
                method: 'POST',
                headers: myHeaders,
                body: formData,
                redirect: 'follow',
            };

            response = fetch(delete_item_url, requestOptions)
                .then(function (response) {

                    if (response.ok) {
                        response.json().then((data) => {
                            $("#itemDiv-"+id).remove()
                            calculateTotalPrice()
                        })
                    }
                })
    }
    </script>
    {% endblock  %}

 